[package]
name = "musicz-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.18"
log = "0.4"
crossbeam = "0.8"
solana-sdk = "1.11.10"
solana-client = "1.11.10"
thiserror = "1.0.29"

