[package]
name = "musicz-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.18"
crossbeam = "0.8"
solana-sdk = "1.10.20"
solana-rpc = "1.10.20"

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
