[package]
name = "musicz-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.20"
log = "0.4.17"
simplelog = "0.12.0"
crossbeam = "0.8"
solana-sdk = "1.11.10"
solana-client = "1.11.10"
thiserror = "1.0.29"
tokio = "1.21.0"